# Generated by Django 4.1.3 on 2023-07-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazzyburger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=' ', upload_to='product_images/'),
        ),
    ]
